import type { GraphNode, GraphEdge, GraphData } from "./types";

const nodes: GraphNode[] = [
  { id: "p1", label: "Attention Is All You Need", type: "paper", content: "Transformer 아키텍처를 제안한 논문. Self-attention 메커니즘만으로 seq2seq 모델을 구성하여 기존 RNN/CNN 기반 모델보다 뛰어난 성능을 달성.", meta: { authors: "Vaswani et al.", year: 2017, citations: 120000 } },
  { id: "p2", label: "BERT", type: "paper", content: "Bidirectional Encoder Representations from Transformers. 사전학습된 양방향 언어 모델로, 다양한 NLP 태스크에서 SOTA 달성.", meta: { authors: "Devlin et al.", year: 2018, citations: 90000 } },
  { id: "p3", label: "GPT-3", type: "paper", content: "175B 파라미터의 대규모 언어 모델. Few-shot learning으로 다양한 태스크 수행 가능함을 입증.", meta: { authors: "Brown et al.", year: 2020, citations: 35000 } },
  { id: "p4", label: "Vision Transformer (ViT)", type: "paper", content: "Transformer를 이미지 분류에 적용. 이미지를 패치로 분할하여 시퀀스로 처리.", meta: { authors: "Dosovitskiy et al.", year: 2020, citations: 25000 } },
  { id: "p5", label: "ResNet", type: "paper", content: "Residual Learning 프레임워크. Skip connection으로 매우 깊은 네트워크 학습 가능.", meta: { authors: "He et al.", year: 2015, citations: 200000 } },
  { id: "p6", label: "Diffusion Models Beat GANs", type: "paper", content: "Diffusion 모델이 이미지 생성에서 GAN을 능가할 수 있음을 입증.", meta: { authors: "Dhariwal & Nichol", year: 2021, citations: 8000 } },
  { id: "p7", label: "CLIP", type: "paper", content: "Contrastive Language-Image Pre-training. 텍스트와 이미지를 동일 임베딩 공간에서 학습.", meta: { authors: "Radford et al.", year: 2021, citations: 15000 } },
  { id: "c1", label: "Self-Attention", type: "concept", content: "시퀀스 내 각 위치가 다른 모든 위치를 참조하여 표현을 계산하는 메커니즘. Query, Key, Value 행렬의 내적으로 구현." },
  { id: "c2", label: "Transformer", type: "concept", content: "Self-attention 기반의 인코더-디코더 아키텍처. 병렬 처리가 가능하여 RNN 대비 학습 속도가 빠름." },
  { id: "c3", label: "Transfer Learning", type: "concept", content: "사전학습된 모델을 다른 태스크에 미세조정하는 학습 패러다임." },
  { id: "c4", label: "Pre-training", type: "concept", content: "대규모 비지도 데이터에서 언어/비전 모델을 사전학습하는 단계." },
  { id: "c5", label: "CNN", type: "concept", content: "Convolutional Neural Network. 합성곱 연산으로 지역적 특징 추출." },
  { id: "c6", label: "Residual Connection", type: "concept", content: "입력을 출력에 더하는 skip connection. 깊은 네트워크의 학습을 안정화." },
  { id: "c7", label: "Diffusion Process", type: "concept", content: "점진적으로 노이즈를 추가한 뒤 역으로 노이즈를 제거하며 데이터를 생성하는 확률적 과정." },
  { id: "c8", label: "Contrastive Learning", type: "concept", content: "유사한 쌍은 가깝게, 다른 쌍은 멀게 임베딩하는 학습 방법." },
  { id: "c9", label: "Multi-modal Learning", type: "concept", content: "텍스트, 이미지, 오디오 등 서로 다른 modality를 함께 학습." },
  { id: "m1", label: "Transformer가 NLP를 바꾼 이유", type: "memo", content: "RNN의 순차 처리 한계를 병렬 처리로 극복. Attention으로 장거리 의존성 문제 해결. 이후 BERT, GPT 등 모든 주요 모델의 기반이 됨." },
  { id: "m2", label: "ViT vs CNN 정리", type: "memo", content: "ViT는 대규모 데이터에서 CNN보다 우수하나, 소규모 데이터에서는 CNN의 inductive bias가 유리. 하이브리드 접근이 실용적." },
  { id: "m3", label: "Diffusion vs GAN 비교", type: "memo", content: "GAN: 빠른 생성, 모드 붕괴 문제. Diffusion: 느리지만 안정적, 다양성 높음. 최근 속도 개선 연구 활발." },
  { id: "d1", label: "NLP 세미나 발표자료.pdf", type: "document", content: "2024년 1월 연구실 세미나에서 발표한 Transformer 계열 모델 서베이 자료." },
  { id: "d2", label: "CV 프로젝트 제안서.pdf", type: "document", content: "ViT 기반 의료 이미지 분류 프로젝트 제안서. ResNet과 성능 비교 포함." },
];

const edges: GraphEdge[] = [
  { id: "e0", source: "p2", target: "p1", type: "citation" },
  { id: "e1", source: "p3", target: "p1", type: "citation" },
  { id: "e2", source: "p4", target: "p1", type: "citation" },
  { id: "e3", source: "p4", target: "p5", type: "citation" },
  { id: "e4", source: "p7", target: "p4", type: "citation" },
  { id: "e5", source: "p7", target: "p3", type: "citation" },
  { id: "e6", source: "p2", target: "p3", type: "citation" },
  { id: "e7", source: "p1", target: "c1", type: "contains" },
  { id: "e8", source: "p1", target: "c2", type: "contains" },
  { id: "e9", source: "p2", target: "c2", type: "contains" },
  { id: "e10", source: "p2", target: "c3", type: "contains" },
  { id: "e11", source: "p2", target: "c4", type: "contains" },
  { id: "e12", source: "p3", target: "c2", type: "contains" },
  { id: "e13", source: "p3", target: "c4", type: "contains" },
  { id: "e14", source: "p4", target: "c1", type: "contains" },
  { id: "e15", source: "p4", target: "c5", type: "contains" },
  { id: "e16", source: "p5", target: "c5", type: "contains" },
  { id: "e17", source: "p5", target: "c6", type: "contains" },
  { id: "e18", source: "p1", target: "c6", type: "contains" },
  { id: "e19", source: "p6", target: "c7", type: "contains" },
  { id: "e20", source: "p7", target: "c8", type: "contains" },
  { id: "e21", source: "p7", target: "c9", type: "contains" },
  { id: "e22", source: "p1", target: "p4", type: "shared_concept" },
  { id: "e23", source: "p5", target: "p4", type: "shared_concept" },
  { id: "e24", source: "p2", target: "p3", type: "shared_concept" },
  { id: "e25", source: "m1", target: "p1", type: "manual" },
  { id: "e26", source: "m1", target: "c2", type: "manual" },
  { id: "e27", source: "m2", target: "p4", type: "manual" },
  { id: "e28", source: "m2", target: "p5", type: "manual" },
  { id: "e29", source: "m3", target: "p6", type: "manual" },
  { id: "e30", source: "d1", target: "p1", type: "manual" },
  { id: "e31", source: "d1", target: "p2", type: "manual" },
  { id: "e32", source: "d1", target: "p3", type: "manual" },
  { id: "e33", source: "d2", target: "p4", type: "manual" },
  { id: "e34", source: "d2", target: "p5", type: "manual" },
  { id: "e35", source: "p6", target: "p7", type: "similarity" },
];

export const sampleGraphData: GraphData = { nodes, edges };
